version: '3'

services:
  postgres:
    image: postgres:11.2-alpine
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpass
      - POSTGRES_DB=projektordb
    ports:
      - "5433:5432"