version: '3'

services:
  postgres:
    image: postgres:11.2-alpine
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpass
      - POSTGRES_DB=projektordb
    ports:
      - "5433:5432"
  objectstorage:
    image: minio/minio:RELEASE.2020-02-20T22-51-23Z
    ports:
      - "9000:9000"
    volumes:
      - ./minio:/data
    environment:
      MINIO_ACCESS_KEY: minio_access_key
      MINIO_SECRET_KEY: minio_secret_key
    command: server /data