name: CI check

on: [push]

jobs:
  gradle-build:
    runs-on: ubuntu-latest
    services:
      database:
        image: postgres:11.2-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: projektordb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache Gradle dependencies
      uses: actions/cache@v1
      with:
        path: ~/.gradle
        key: ${{ runner.os }}-gradle-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties*') }}-${{ hashFiles('**/*gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties*') }}
    - name: Build with Gradle
      env:
        DB_URL: "jdbc:postgresql://localhost:5432/projektordb"
      run: ./gradlew check

  node-script-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: node-script test
      run: |
        cd publishers/node-script
        yarn install
        yarn test

  ui-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Cache UI Node dependencies
      uses: actions/cache@v1
      with:
        path: ui/node_modules
        key: ${{ runner.os }}-ui-node-modules-${{ hashFiles('ui/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-ui-node-modules

    - name: ui test
      run: |
        cd ui
        yarn install
        yarn test

    - name: cypress-common install
      run: |
        cd cypress-common
        yarn install

    - name: ui install
      run: |
        cd ui
        yarn install

    - name: ui start server
      run: |
        cd ui
        yarn start &

    - name: UI Cypress run
      uses: cypress-io/github-action@v1
      with:
        wait-on: 'http://localhost:1234'
        working-directory: ui
        install: false

  assemble-and-functional-test:
    runs-on: ubuntu-latest
    services:
      database:
        image: postgres:11.2-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: projektordb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install Cypress dependencies
      run: |
        apt-get install libgtk2.0-0 libgtk-3-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
    - name: Cache UI Node dependencies
      uses: actions/cache@v1
      with:
        path: ui/node_modules
        key: ${{ runner.os }}-ui-node-modules-${{ hashFiles('ui/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-ui-node-modules

    - name: ui install
      run: |
        cd ui
        yarn install
    - name: cypress-common install
      run: |
        cd cypress-common
        yarn install
    - name: functional-test install
      run: |
        cd functional-test
        yarn install
    - name: Run functional tests
      env:
        DB_URL: "jdbc:postgresql://localhost:5432/projektordb"
      run: ./gradlew :functional-test:functionalTest
