on:
  push:
    paths-ignore:
      - 'functional-test/**'
      - 'ui/**'

name: Gradle plugin Java version test

jobs:
  build:
    name: Gradle plugin Java version test
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Gradle dependencies
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches/modules-2
          key: ${{ runner.os }}-gradle-modules-${{ hashFiles('**/*gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-modules-
      - name: Build with Gradle
        env:
          PROJEKTOR_TOKEN: ${{ secrets.PROJEKTOR_TOKEN }}
        run: ./gradlew :publishers:gradle-plugin:build --no-build-cache -x :publishers:gradle-plugin:functionalTest
