on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'gradle_*' # Push events to matching gradle_*, i.e. gradle_1.0.0

name: Release Gradle plugin

jobs:
  build:
    name: Publish Gradle plugin release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Gradle dependencies
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches/modules-2
          key: ${{ runner.os }}-gradle-modules-${{ hashFiles('**/*gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-modules-

      - name: Build
        env:
          PROJEKTOR_TOKEN: ${{ secrets.PROJEKTOR_TOKEN }}
        run: ./gradlew :publishers:gradle-plugin:build

      - name: Publish plugin
        run: ./gradlew :publishers:gradle-plugin:publishPlugin -Pgradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }} -Pgradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}
